language: node_js

node_js:
  - "4.2.1"

os:
  - linux
  - osx

before_script:
  - npm install -g mocha
  - export CC=clang
  - export CXX=clang++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libssl-dev
      - gcc-4.9
      - g++-4.9
      - lcov